=== Erik-git21/XML-Schema-Validation-Testing/schema.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Voliteľná anotácia s dokumentáciou -->
    <xsd:annotation>
        <xsd:documentation>DPHv21 v1.2</xsd:documentation>
    </xsd:annotation>

    <!-- Definície jednoduchých typov -->
    <xsd:simpleType name="emptyStr">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value=""/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="optBool">
        <xsd:union memberTypes="xsd:boolean emptyStr"/>
    </xsd:simpleType>

    <xsd:simpleType name="date">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(((([0])?[1-9])|([1-2][0-9])|([3][0]))[.]((([0])?[13-9])|([1][0-2]))[.]([0-9][0-9][0-9][0-9]))"/>
            <xsd:pattern value="([3][1][.]((([0])?[13578])|([1][02]))[.]([0-9][0-9][0-9][0-9]))"/>
            <xsd:pattern value="(((([0])?[1-9])|([1][0-9])|([2][0-8]))[.]([0])?[2][.]([0-9][0-9][0-9][0-9]))"/>
            <xsd:pattern value="([2][9][.]([0])?[2])[.][0-9][0-9][13579][26]"/>
            <xsd:pattern value="([2][9][.]([0])?[2])[.][0-9][0-9][02468][048]"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hlavickaOptDate">
        <xsd:union memberTypes="date emptyStr"/>
    </xsd:simpleType>

    <xsd:simpleType name="optInt">
        <xsd:union memberTypes="xsd:integer emptyStr"/>
    </xsd:simpleType>

    <xsd:simpleType name="optDec">
        <xsd:union memberTypes="decimalWithTwoDec emptyStr"/>
    </xsd:simpleType>

    <xsd:simpleType name="decimalWithTwoDec">
        <xsd:restriction base="xsd:decimal">
            <xsd:totalDigits value="12"/>
            <xsd:fractionDigits value="2"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Definície zložených typov -->
    <xsd:complexType name="hlavicka">
        <xsd:sequence>
            <xsd:element name="identifikacneCislo" type="identifikacneCislo"/>
            <xsd:element name="dic" type="xsd:string"/>
            <xsd:element name="danovyUrad" type="xsd:string"/>
            <xsd:element name="nevzniklaPov" type="optBool"/>
            <xsd:element name="typDP" type="typDP"/>
            <xsd:element name="osoba" type="osoba"/>
            <xsd:element name="zdanObd" type="zdanObd"/>
            <xsd:element name="meno" type="meno"/>
            <xsd:element name="adresa" type="adresa"/>
            <xsd:element name="opravnenaOsoba" type="opravnenaOsoba"/>
            <xsd:element name="datumVyhlasenia" type="hlavickaOptDate"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="identifikacneCislo">
        <xsd:sequence>
            <xsd:element name="kodStatu" type="xsd:string"/>
            <xsd:element name="cislo" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="typDP">
        <xsd:sequence>
            <xsd:element name="rdp" type="optBool"/>
            <xsd:element name="odp" type="optBool"/>
            <xsd:element name="ddp" type="optBool"/>
            <xsd:element name="datumZisteniaDdp" type="hlavickaOptDate"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="osoba">
        <xsd:sequence>
            <xsd:element name="platitel" type="optBool"/>
            <xsd:element name="registrovana" type="optBool"/>
            <xsd:element name="inaPovinna" type="optBool"/>
            <xsd:element name="zdanitelna" type="optBool"/>
            <xsd:element name="zastupca" type="optBool"/>
            <xsd:element name="zastupca69aa" type="optBool"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="zdanObd">
        <xsd:sequence>
            <xsd:element name="mesiac" type="xsd:string"/>
            <xsd:element name="stvrtrok" type="xsd:string"/>
            <xsd:element name="rok" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="meno">
        <xsd:sequence>
            <xsd:element name="riadok" type="xsd:string" maxOccurs="4"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="adresa">
        <xsd:sequence>
            <xsd:element name="ulica" type="xsd:string"/>
            <xsd:element name="cislo" type="xsd:string"/>
            <xsd:element name="psc" type="xsd:string"/>
            <xsd:element name="obec" type="xsd:string"/>
            <xsd:element name="telefon" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="opravnenaOsoba">
        <xsd:sequence>
            <xsd:element name="menoPriezvisko" type="xsd:string"/>
            <xsd:element name="telefon" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="telo">
        <xsd:sequence>
            <!-- viaceré r# elementy, každý s použitím optDec -->
            <xsd:element name="r01" type="optDec"/>
            <xsd:element name="r02" type="optDec"/>
            <xsd:element name="r03" type="optDec"/>
            <!-- ...ostatné r elementy... -->
        </xsd:sequence>
    </xsd:complexType>

    <!-- Koreňový element -->
    <xsd:element name="dokument">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="hlavicka" type="hlavicka"/>
                <xsd:element name="telo" type="telo"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Erik-git21/XML-Schema-Validation-Testing/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<dokument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <hlavicka>
        <identifikacneCislo>
            <kodStatu>SK</kodStatu>
            <cislo>123456</cislo>
        </identifikacneCislo>
        <dic>0123456789</dic>
        <danovyUrad>Bratislava</danovyUrad>
        <nevzniklaPov>true</nevzniklaPov>
        <typDP>
            <rdp>false</rdp>
            <odp>false</odp>
            <ddp>true</ddp>
            <datumZisteniaDdp>31.12.2023</datumZisteniaDdp>
        </typDP>
        <osoba>
            <platitel>true</platitel>
            <registrovana>false</registrovana>
            <inaPovinna>true</inaPovinna>
            <zdanitelna>false</zdanitelna>
            <zastupca>true</zastupca>
            <zastupca69aa>false</zastupca69aa>
        </osoba>
        <zdanObd>
            <mesiac>01</mesiac>
            <stvrtrok>1</stvrtrok>
            <rok>2023</rok>
        </zdanObd>
        <meno>
            <riadok>Meno Priezvisko</riadok>
        </meno>
        <adresa>
            <ulica>Hlavná</ulica>
            <cislo>123</cislo>
            <psc>12345</psc>
            <obec>Bratislava</obec>
            <telefon>+421900000000</telefon>
            <email>test@example.com</email>
        </adresa>
        <opravnenaOsoba>
            <menoPriezvisko>Ján Novák</menoPriezvisko>
            <telefon>+421900000001</telefon>
            <email>novak@example.com</email>
        </opravnenaOsoba>
        <datumVyhlasenia>31.12.2023</datumVyhlasenia>
    </hlavicka>
    <telo>
        <r01>100.00</r01>
        <r02>200.50</r02>
        <r03>300.75</r03>
    </telo>
</dokument>
